### ISSUE TITLE
Help-me

### ISSUE THREAD

**Issue by TeePee** [swisskyrepo/WHID_Toolkit#1]
Salut swissky ;-)

J'ai fais mon béné en essayant de passer le clavier en azerty en suivant les consignes sur https://swisskyrepo.github.io/WhidInjector/
Du coup ma clé est HS, j'essaye de la réinstaller, mais je comprends pas trop la manip avec l'aimant ?
N'est-il pas possible d'avoir le fichier.bin pour la flasher directement sans avoir à recompiler via l'IDE-Arduino ?

STP

**Comment by swisskyrepo** [comment]
Je n'ai plus le fichier.bin, 
De mémoire il fallait passer un aimant sous la clef en faisant des "aller-retour" quand elle était branchée, tout en spammant le bouton "upload" de l'IDE

**Comment by TeePee** [comment]
C'est bon swissky, j'y est passé un peu de temps mais c'est flashé et fonctionnel, merci.
